### ISSUE TITLE
"Invalid dev and peer dependency relationship" errors when devDependency is "*"

### ISSUE THREAD

**Issue by ryanbraganza** [Thinkmill/manypkg#27]
In our monorepo, we have a package (A) with a peerDependency declared on another internal package (B).

The "Internal devDependencies are not *" implies the devDependency of A on B should be "*". `manypkg fix` enforces this.

However, the "Invalid dev and peer dependency relationship" does not accept "*" to be valid when a peerDependency is declared.

Expected behaviour: Any peerDependency is compatible with a devDependency of "*".

version: @manypkg/cli@^0.8.0

@Noviny has the context on this.

**Comment by Noviny** [comment]
Just adding some clarity after further discussion:

We have a tree state of:

```
pkgA@1.0.0
pkB@1.0.0
  devDependency: pkgA@^1.0.0
  peerDependency: pkgA@^1.0.0
```

There are two manyPkg rules:
1. internal dev dep must be `*`
2. all peerDependencies must have a devDependency of a matching version

Note that the peerDependency does not want to be `*` because that will cause problems.

Possible ways forward:

1. Allow a mismatch between dev and peerDep for internal packages only (a rule exception)
2. Allow devDeps with a peerDep to match instead of being `*` (a rule exception)
3. Revert the devDeps change

Opinions:

1. This option gains us nothing, while complicating a rule outside of the main concern. The reason for the `*` rule was to prevent bumps, but the existence of the peerDep means bumps are still necessary.
2. Probably the best way forward, since it locates the concerns more neatly (to me)
3. I'd rather not, but maybe?

@mitchellhamilton if you're fine with it, I might implement 2.

**Comment by mitchellhamilton** [comment]
The dev peer dep rule should be checking that the peer dep range is a subset of the dev dep range but I just checked and I passed the arguments to sembear.contains in the wrong order so if you swap the order of the arguments, this will be fixed.

**Comment by Noviny** [comment]
PR may be slightly slower as I'm gonna write some tesssstttssssss
